### PR TITLE
Local Notification

### PR DESCRIPTION
**Pull request by mustofa-al**
## Description

Hello @syedmurtaza108, i added local notification support, just like alice. But it still not possible for now to stack the notification like they did.

I updated the readme too for usage.

But, due to conflict to another plugin in my project, i downgrade the chopper version to 4.0.5.

## Type of Change

- [x] ✨ New feature: Local Notification

### CODE REVIEW

**Comment by syedmurtaza108** [comment]
Salam @mustofa-al, the feature really looks amazing🥳. I will definitely look into this as soon as possible for me. Meanwhile I request you to add tests for this feature as I don't find any test.

Thank you for your contribution🙌

**Comment by mustofa-al** [comment]
Yeah i think i need to test how notification initialized & show as soon as possible, but could you guide me what else to test?

**Comment by syedmurtaza108** [comment]
@mustofa-al By test I meant to add unit and widget tests for the feature. To get a basic idea of how to add tests, you may see [https://github.com/syedmurtaza108/chucker-flutter/tree/master/test](https://github.com/syedmurtaza108/chucker-flutter/tree/master/test)

**Comment by mustofa-al** [comment]
@syedmurtaza108 yeah i know. Wait, i'm working on

**Comment by mustofa-al** [comment]
@syedmurtaza108 hello, i'm done with my changes, but how to update changes to this pull request? or would be better to create new pull request?

**Comment by syedmurtaza108** [comment]
@mustofa-al Thank you for updates. 
- You don't need to update changes in the PR. They are automatically reflected in the PR as soon as you make changes in your `master` branch.
- I request you to plz create your PR again from [dev](https://github.com/syedmurtaza108/chucker-flutter/tree/dev) branch instead of `master`. Because we will be releasing a beta version first for the public to check the stability of the feature before merging it to `master` branch. 
- After we get satisfied, we will merge it to `master` and I will make these changes public on `pub.dev`

**Comment by syedmurtaza108** [comment]
This PR is being closed in respect of [PR#21](https://github.com/syedmurtaza108/chucker-flutter/pull/21).

**Pull request closed without merging**
